name: Notify Vercel Server

on:
  workflow_dispatch:
  deployment_status:

jobs:
  notify_vercel:
    runs-on: ubuntu-latest

    steps:
      - name: Log deployment status
        run: |
          echo "Deployment status: ${{ github.event.deployment_status.state }}"
      - name: Log deployment status
        run: |
          echo "Deployment status: ${{ github.event.deployment_status.state }}"

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Call Vercel-deployed Node.js API
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          echo "Branch name: $branch_name"
          curl -X POST ${{ secrets.SLACK_WEBHOOK_API_URL }}/vercel-deploy-hook \
          -H "Content-Type: application/json" \
          -d '{
                "name": "${{ secrets.PROJECT_NAME }}",
                "target": "production",
                "gitSource": {
                  "ref": "$branch_name",
                  "message": "${{ github.event.head_commit.message }}"
                },
                "createdAt": "${{ github.event.head_commit.timestamp }}"
              }
            '
